(function () {
  var units = [["天", 864e5], ["時", 36e5], ["分", 6e4], ["秒", 1e3]];
  function format(milliseconds) { var remaining = Math.max(0, milliseconds); return units.map(function (unit) { var value = Math.floor(remaining / unit[1]); remaining %= unit[1]; return value + unit[0]; }).join(" "); }
  function write(identifier, value) { var element = document.getElementById(identifier); if (element) element.textContent = value; }
  function localDate(value) { var parts = value.split("-"); return new Date(Number(parts[0]), Number(parts[1]) - 1, Number(parts[2])); }
  function birthDate() { var label = document.querySelector(".date-card p"); var match = label && label.textContent.match(/(\d{4})\.(\d{2})\.(\d{2})/); return match ? { year: Number(match[1]), month: Number(match[2]) - 1, day: Number(match[3]) } : null; }
  function writeAge(now, birth) { if (!birth) return; var age = now.getFullYear() - birth.year; var anniversary = new Date(now.getFullYear(), birth.month, birth.day); if (now < anniversary) age -= 1; var birthdayCount = document.getElementById("birthday"); var card = birthdayCount && birthdayCount.parentNode; var title = card && card.querySelector("h3"); if (!title) return; var ageElement = document.getElementById("age"); if (!ageElement) { ageElement = document.createElement("span"); ageElement.id = "age"; ageElement.className = "birthday-age"; title.parentNode.insertBefore(ageElement, title.nextSibling); var style = document.createElement("style"); style.textContent = ".birthday-age{display:block;margin-top:7px;color:var(--blue);font-size:clamp(18px,2vw,28px);font-weight:bold}"; document.head.appendChild(style); } ageElement.textContent = age + " 歲"; }
  function renderHoliday(now) { var schedule = window.chinaStatutoryHolidays || {}; var holidays = []; Object.keys(schedule).forEach(function (year) { holidays = holidays.concat(schedule[year]); }); var active = holidays.find(function (holiday) { var start = localDate(holiday.start); var end = localDate(holiday.end); end.setDate(end.getDate() + 1); return now >= start && now < end; }); var next = holidays.find(function (holiday) { return localDate(holiday.start) > now; }); var holiday = active || next; if (!holiday) { write("holiday-name", "節假日安排待更新"); write("holiday-status", "—"); write("holiday-days", ""); write("holiday-range", ""); return; } var startDate = localDate(holiday.start); var endDate = localDate(holiday.end); var exclusiveEnd = new Date(endDate); exclusiveEnd.setDate(exclusiveEnd.getDate() + 1); write("holiday-name", holiday.name); write("holiday-status", active ? "假期進行中 · 尚餘 " + format(exclusiveEnd - now) : "距離開始 · " + format(startDate - now)); write("holiday-days", "共 " + holiday.days + " 天休假"); write("holiday-range", holiday.start.replace(/-/g, ".") + " — " + holiday.end.replace(/-/g, ".")); }
  function update() { var now = new Date(); var today = new Date(now.getFullYear(), now.getMonth(), now.getDate()); var tomorrow = new Date(today); tomorrow.setDate(tomorrow.getDate() + 1); var nextMonday = new Date(today); nextMonday.setDate(nextMonday.getDate() + ((8 - nextMonday.getDay()) % 7 || 7)); var nextMonth = new Date(now.getFullYear(), now.getMonth() + 1, 1); var nextYear = new Date(now.getFullYear() + 1, 0, 1); var birth = birthDate(); var birthday = birth && new Date(now.getFullYear(), birth.month, birth.day); if (birthday && birthday <= now) birthday.setFullYear(birthday.getFullYear() + 1); write("day", format(tomorrow - now)); write("week", format(nextMonday - now)); write("month", format(nextMonth - now)); write("year", format(nextYear - now)); write("birthday", birthday ? "距離下個生日：" + format(birthday - now) : "—"); writeAge(now, birth); write("today", now.getFullYear() + "年" + (now.getMonth() + 1) + "月" + now.getDate() + "日"); renderHoliday(now); }
  update(); window.setInterval(update, 1000);
}());
